---
title: "Passwords"
author: "Ifeoma Egbogah"
date: "1/18/2020"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load packages
```{r}

library(here)
library(tidyverse)
library(ggthemes)
library(extrafont)
library(lubridate)
loadfonts(device = "win")

```

##Data
```{r}

passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv')

```

##Filtering data by time unit as to enable conversion to similar time units.
```{r}

years <- passwords%>%
  filter(time_unit == "years")%>%
  mutate(weeks = value * 52,
         time = duration(weeks, "weeks"),
         time2 = as.numeric(time, "seconds"))%>%
  select(-time, -weeks)

months <- passwords%>%
  filter(time_unit == "months")%>%
  mutate(weeks = value * 4,
         time = duration(weeks, "weeks"),
         time2 = as.numeric(time, "seconds"))%>%
  select(-time, -weeks)

weeks <- passwords%>%
  filter(time_unit == "weeks")%>%
  mutate(time = duration(value, "weeks"),
         time2 = as.numeric(time, "seconds"))%>%
  select(-time)

days <- passwords%>%
  filter(time_unit == "days")%>%
  mutate(time = duration(value, "days"),
         time2 = as.numeric(time, "seconds"))%>%
  select(-time)

hours <- passwords%>%
  filter(time_unit == "hours")%>%
  mutate(time = duration(value, "hours"),
         time2 = as.numeric(time, "seconds"))%>%
  select(-time)

mins <- passwords%>%
  filter(time_unit == "minutes")%>%
  mutate(time = duration(value, "minutes"),
         time2 = as.numeric(time, "seconds"))%>%
  select(-time)

sec <- passwords%>%
  filter(time_unit == "seconds")%>%
  mutate(time2 = value)

passwords2 <- bind_rows(years, months, weeks, days, hours, mins, sec)

passwords3 <- passwords2%>%
  mutate(time3 = time2/3600) #changing to hours


```


```{r}

pass <- passwords3%>%
  filter(!is.na(category))%>%
  group_by(category)%>%
  summarise(mean_time = mean(time3))%>%
  mutate(category = str_to_title(category),
         category = str_replace(category, "-", " "),
         category = fct_reorder(category, mean_time))%>%
  ggplot(aes(category, mean_time))+
  geom_segment(aes(xend = category, yend = 0), size = 1.2)+
  geom_point(size = 3, colour = "black")+
  geom_label(aes(category, mean_time - 1000, label = category), family = "Pristina", colour = "darkred", nudge_x = 0.35, size = 5)+
  scale_y_continuous(expand = c(0, 0), limits = c(0, 69000), breaks = seq(0, 69000, 10000), labels = scales::label_comma())+
  coord_flip()+
  theme_fivethirtyeight()+
  theme(axis.text.y = element_blank(),
        axis.title.x = element_text(family = "Modern No. 20", size = 15, colour = "black"),
        axis.title.y = element_text(family = "Modern No. 20", size = 15, colour = "black"),
        plot.margin =  margin(1, 1, 1, 1, "cm"),
        plot.title = element_text(family = "Modern No. 20", colour = "black", size = 17),
        plot.caption = element_text(family = "Pristina", colour = "darkred", size = 12.8))+
  labs(x = "Category",
       y = "Time (hrs)",
       title = "Categories and Time in Hours to Crack Passwords By Online Guessing",
       caption = "Source: Information is Beautiful | Visualization: @negbogah")

ggsave(here("pass.png"), pass, width = 10, height = 8)

```



