---
title: "Australia Fires"
author: "Ifeoma Egbogah"
date: "1/12/2020"
output: 
  ioslides_presentation: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

##Load Packages
```{r}

library(here)
library(scales)
library(tidyverse)
library(lubridate)
library(hrbrthemes)
library(ggthemes)
library(extrafont)
font_import()
loadfonts(device = "win")

```

##Get the Data
```{r}

rainfall <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/rainfall.csv')

temperature <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/temperature.csv')


# IF YOU USE THIS DATA PLEASE BE CAUTIOUS WITH INTERPRETATION
nasa_fire <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/MODIS_C6_Australia_and_New_Zealand_7d.csv')


# For JSON File of fires
url <- "http://www.rfs.nsw.gov.au/feeds/majorIncidents.json"

aus_fires <- sf::st_read(url)

```


```{r}

rainfall2 <- rainfall%>%
  unite("date", year:day, sep = "-", remove = FALSE)%>%
  mutate(date = ymd(date))


rain <- rainfall2%>%
  mutate(month = month(date, label = TRUE))%>%
  filter(!is.na(rainfall),
         year >= "1860",
         year < "2020")%>%
  group_by(year, month, day)%>%
  summarise(rain_mean = mean(rainfall))%>%
  group_by(year, month)%>%
  summarise(rain_sum = sum(rain_mean))%>%
  mutate(decade = 30 * (year %/%30))%>%
  group_by(decade, month)%>%
  summarise(rain_mean2 = mean(rain_sum))%>%
  mutate(label = case_when(decade == "1860" ~	"1860 - 1889 (Avg. Rainfall = 99.3mm)",
                           decade == "1890" ~ "1890 - 1919 (Avg. Rainfall = 74.0mm)",
                           decade == "1920" ~ "1920 - 1949 (Avg. Rainfall = 69.5mm)",
                           decade == "1950" ~ "1950 - 1979 (Avg. Rainfall = 75.6mm)",
                           decade == "1980" ~ "1980 - 2009 (Avg. Rainfall = 69.0mm)",
                           decade == "2010" ~ "2010 - 2019 (Avg. Rainfall = 70.4mm)"))%>%
    ggplot(aes(month, rain_mean2, group = decade))+
  geom_point(size = 2, colour = "skyblue")+
  geom_line(size = 1, colour = "skyblue")+
 #geom_mark_circle(aes(fill = rain_sum, filter = month == "Mar"))+
  facet_wrap(~label)+
  scale_y_continuous(limits = c(0, 160), labels = label_number_si(unit = "mm"))+
  theme_ft_rc()+
  theme(panel.grid.minor = element_blank(),
        axis.title.y = element_text(family = "Gabriola", face = "bold", colour = "white", hjust = 0.5, vjust = 0.9, size = 15),
        axis.title.x = element_text(family = "Gabriola", face = "bold", colour = "white", hjust = 0.5, vjust = 0.2, size = 15),
        plot.title = element_text(family = "Poor Richard", colour = "skyblue"),
        plot.caption = element_text(family = "Rage Italic", face = "bold", colour = "white", size = 12),
        strip.text = element_text(size = 19, face = "bold", colour = "white", family = "Gabriola"))+
  labs(x = "Month",
       y = "Rainfall (mm)",
       title = "Average Total Annual Rainfall (mm) in Australia Faceted By Thirty Year Interval Period from 1860 - 2019",
       caption = "Source: Australian Bureau Of Meterology | Visualization: @negbogah")



temp <- temperature%>%
  mutate(month = month(date, label = TRUE),
         year = year(date),
         day = day(date))%>%
  filter(!is.na(temperature),
         year >= "1910",
         temp_type == "max",
         year < "2020")%>%
  group_by(year, month, day)%>%
  summarise(temp_mean_day = mean(temperature))%>%
  group_by(year, month)%>%
  summarise(temp_mean = mean(temp_mean_day))%>%
  mutate(decade = 30 * (year %/%30))%>%
  group_by(decade, month)%>%
  summarise(temp = mean(temp_mean))%>%
  mutate(label = case_when(decade == "1890" ~ "1910 - 1919 (Avg. Temp = 21.4°C)",
                           decade == "1920" ~ "1920 - 1949 (Avg. Temp = 21.1°C)",
                           decade == "1950" ~ "1950 - 1979 (Avg. Temp = 21.8°C)",
                           decade == "1980" ~ "1980 - 2009 (Avg. Temp = 22.3°C)",
                           decade == "2010" ~ "2010 - 2019 (Avg. Temp = 23.0°C)"))%>%
  ggplot(aes(month, temp, group = decade))+
  geom_point(size = 2, colour = "gold")+
  geom_line(size = 1, colour = "gold")+
  facet_wrap(~label)+
  scale_y_continuous(labels = label_number_si(unit = "°C"), breaks = seq(0, 30, 10), limits = c(0, 30))+
  theme_ft_rc()+
  theme(panel.grid.minor = element_blank(),
        axis.title.y = element_text(family = "Gabriola", face = "bold", colour = "white", hjust = 0.5, vjust = 0.9, size = 15),
        axis.title.x = element_text(family = "Gabriola", face = "bold", colour = "white", hjust = 0.5, vjust = 0.2, size = 15),
        plot.title = element_text(family = "Poor Richard", colour = "gold"),
        plot.caption = element_text(family = "Rage Italic", face = "bold", colour = "white", size = 12),
        strip.text = element_text(size = 19, face = "bold", colour = "white",family = "Gabriola"))+
  labs(x = "Month",
       y = expression(paste("Temperature ("*degree*C*")")),
       title = "Mean Annual Temperature in Australia Faceted By Thirty Year Interval Period from 1910 - 2019",
       caption = "Source: Australian Bureau Of Meterology | Visualization: @negbogah")

#ggsave("rain.jpeg", rain, width = 12, height = 7)
#ggsave("temp.jpeg", temp, width = 12, height = 7)

```

