---
title: "Philadelphia Parking Violations"
author: "Ifeoma Egbogah"
date: "12/16/2019"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(colorspace)
library(tidyverse)
library(sf)
library(viridis)
library(ggthemes)
library(extrafont)
font_import()
loadfonts(device = "win")

```


```{r}

tickets <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-03/tickets.csv")

##Shapefile of Philadelphia (map, river snd watershed) from www.opendataphilly.org

philly <- read_sf("Philadelphia/Zoning_PreAug2012/Zoning_PreAug2012.shp")

philly <- st_transform(philly, crs = 4326)

philly_watershed <- read_sf("Philadelphia/Hydrographic_Features_Poly/Hydrographic_Features_Poly.shp")

philly_watershed <- st_transform(philly_watershed, crs = 4326)

philly_river <- read_sf("Philadelphia/Philly_areawater/tl_2013_42101_areawater.shp")

philly_river <- st_transform(philly_river, crs = 4326)

```


```{r}

watershed <- philly_watershed%>%
  st_crop(xmin = -75.30, xmax = -74.95, ymin = 39.80, ymax = 40.05)

water <- philly_watershed%>%
  st_intersection(., philly)

tick <- tickets%>%
  filter(lon >= -75.3)%>%
  filter(lat >= 39.8)%>%
  ggplot()+
  geom_sf(data = philly_river, colour = darken("skyblue"), fill = "skyblue")+
  geom_sf(data = watershed, colour = darken("skyblue"), fill = "skyblue")+
  geom_sf(data = philly, fill = "transparent", colour = "grey65")+
  geom_bin2d(aes(lon, lat), binwidth = 0.001, alpha = 0.7)+
  scale_fill_viridis_c(option = "plasma", alpha = 0.7, 
                       guide = guide_colourbar(direction = "horizontal",
                                               title.position = "top",
                                               title.hjust = 0.5,
                                               barheight = unit(2, units = "mm"),
                                               barwidth = unit(50, units = "mm")))+
  theme_light()+
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        panel.border = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        legend.position = "bottom",
        plot.title = element_text(family = "Rage Italic", size = 22, hjust = 0.5),
        plot.caption = element_text(family = "Poor Richard", size = 10))+
  labs(fill = "Density",
       title = "Density of Traffic Violation in Philadelphia, USA in 2017",
       caption = "Data: Open Philly Data | Visualization: Ifeoma Egbogah")


ggsave("ticket2.jpeg", tick, width = 10, height = 10)


```

