---
title: "Moore's Law"
author: "Ifeoma Egbogah"
date: "9/11/2019"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(ggthemes)
library(gameofthrones)
library(extrafont)
loadfonts()
#font_import(device = "win")


cpu <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-03/cpu.csv")


moore_law <- cpu%>%
  filter(!is.na(transistor_count), !is.na(area))%>%
  ggplot(aes(date_of_introduction, transistor_count))+
  geom_point(aes(size = area, colour = designer))+
  geom_text(aes(label = designer), family = "Gabriola", size = 4, hjust = -0.2, vjust = -0.2, check_overlap = TRUE)+
  #geom_smooth(method = "auto", lty = 2, colour = "darkred")+
  scale_colour_got_d(option = "wildfire")+
  scale_x_continuous(breaks = seq(1970, 2020, 5), limits = c(1970, 2022))+
  scale_y_log10(labels = scales::comma)+
  theme_minimal()+
  theme(plot.title = element_text(family = "Leelawadee UI", colour = "black"),
        axis.title = element_text(family = "Microsoft Himalaya", size = 15, colour = "black"),
        plot.subtitle = element_text(family = "Microsoft Himalaya", size = 15),
        plot.caption = element_text(family = "Gabriola", size = 11))+
  guides(colour = F)+
  labs(y = "Transistor Count (Log)",
       x = "Date of Introduction",
       title = "The Number of Transistors (1970 - 2018)",
       subtitle = "Moore's Law: The Number of Transistors Doubles Approximately Every Two Years",
       size = expression(paste("Area of Chip ", (mm^2))),
       caption = "Data Source: Wikipedia | Visualization: Ifeoma Egbogah")



area_of_chip <- cpu%>%
  filter(!is.na(transistor_count), !is.na(area))%>%
  mutate(year = as.integer(date_of_introduction))%>%
  group_by(designer, year)%>%
  ggplot(aes(transistor_count, area, label = designer))+
  geom_point(aes(size = area, colour = designer), show.legend = FALSE)+
  geom_text(hjust = -0.2, vjust = -0.2, check_overlap = TRUE)+
  geom_smooth(method = "auto")+
  scale_x_continuous(labels = scales::comma)+
  scale_colour_got_d(option = "tully")+
  guides(size = F, colour = F)+
  theme_minimal()+
  theme(plot.title = element_text(family = "Leelawadee UI", colour = "black", size = 30),
        axis.title = element_text(family = "Microsoft Himalaya", size = 19, colour = "black"),
        plot.subtitle = element_text(family = "Microsoft Himalaya", size = 18),
        plot.caption = element_text(family = "Gabriola", size = 11)) +
    labs(title = "The Number of Transistors on Intergrated Circuit Chip",
       subtitle = "Processing power amongst other things is mostly dependent on the transistor count in a chip. The Transistor count also determines the size or area footprint of the chip. 
The plot shows the Area of chip over time plateaued at about 800 sq mm and a regression analysis shows no significant increase in area is likely.
Newer technologies favour smaller footprint or Area of chip while still boasting high processing power. In this bracket you have chips with transistor count between\n5 Billion - 10 Billion integrated within an area of less than 300 sq mm. 
While some older devices still use the likes of IBM processors with similar processing power and bigger footprint, newer designers go for the likes of AMD,\nQualcomm and Apple, which provides the high processing power in a much reduced area, with Qaulcomm boasting the highest processing power close to 20 Billion transistors within 400 sq mm",
       y = expression(paste("Area of Chip ", (mm^2))),
       x = "Transistor Count",
       caption = "Data Source: Wikipedia | Visualization: Ifeoma Egbogah")


ggsave("area.png", area_of_chip, height = 7, width = 15)
ggsave("mooore.png", moore_law, height = 5, width = 10)
```

