---
title: "Wildlife Impact"
author: "Ifeoma Egbogah"
date: "8/1/2019"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(ggalluvial)
library(lubridate)
library(ggthemes)
library(drlib)
library(gameofthrones)
library(sf)
library(maps)
library(extrafont)
library(acs)
library(spData)
font_import()
loadfonts(device = "win")


wildlife_impacts <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-23/wildlife_impacts.csv")

```


```{r}

wildlife <- wildlife_impacts%>%
  filter(species != "Unknown bird - medium")%>%
  filter(species != "Unknown bird - small")%>%
  filter(species != "Unknown bird - large")%>%
  filter(species != "Unknown bird")%>%
  filter(!is.na(time_of_day))%>%
  filter(!is.na(height))%>%
  filter(!is.na(speed))%>%
  mutate(level_height = cut(height, breaks = unique(quantile(height, probs = seq(0, 1, length.out = 5))), include.lowest = TRUE))%>%
  count(species = fct_lump(species, 20), level_height, sort = TRUE)%>%
  mutate(species = fct_reorder(species, n))%>%
  ggplot(aes(species, n))+
  geom_col(aes(fill = level_height), width = .6)+
  coord_flip()+
  scale_fill_got_d(option = "Tully")+
  labs(y = "Wildlife Count",
       x = "WIldlife",
       title = "Top 20 Wildlife Struck By Airplane in North America",
       subtitle = "Showing height of impact",
       caption = "Source: | Visualization: Ifeoma Egbogah",
       fill = "Height")+
  theme_solarized_2()+
  theme(plot.title = element_text(family = "Nirmala UI Semilight", colour = "darkred"),
        plot.subtitle = element_text(family = "Nirmala UI Semilight"),
        axis.title = element_text(family = "Segoe UI Historic"),
        axis.text.y = element_text(family = "Segoe UI Historic"),
        legend.text = element_text(family = "Nirmala UI Semilight"),
        legend.title = element_text(family = "Nirmala UI Semilight"),
        plot.caption = element_text(colour = "darkred"))


wildlife1 <- wildlife_impacts%>%
  filter(!is.na(time_of_day))%>%
  group_by(incident_year, time_of_day)%>%
  summarise(time_total = n())%>%
  ungroup()%>%
  group_by(incident_year)%>%
  mutate(day_total = sum(time_total),
         pct = time_total/day_total)%>%
  ggplot(aes(incident_year, time_total))+
  geom_col(aes(fill = time_of_day))+
  theme_solarized()+
  scale_fill_got_d(option = "Tully")+
  scale_x_continuous(breaks = seq(1990, 2019, 5))+
  labs(x = "Year",
       y = "Total",
       fill = "Time of Day",
       title = " Aircraft Strike On Wildlife In North America From 1990 - 2018",
       subtitle = "Catergorised by impact on the time of day",
       caption = "Source: FAA | Visualization: Ifeoma Egbogah")

```


##GGalluvial Plot
```{r}
wildlife2 <- wildlife_impacts%>%
  filter(species != "Unknown bird - medium")%>%
  filter(species != "Unknown bird - small")%>%
  filter(species != "Unknown bird - large")%>%
  filter(species != "Unknown bird")%>%
  filter(!is.na(time_of_day))%>%
  filter(!is.na(height))%>%
  filter(!is.na(sky))%>%
  mutate(level_height = cut(height, breaks = unique(quantile(height, probs = seq(0, 1, length.out = 6))), include.lowest = TRUE))%>%
  mutate(level = case_when(level_height == "[0,30]" ~ "Low",
                           level_height == "(30,500]" ~ "Mid",
                           level_height == "(500,2e+04]" ~ "High"))%>%
  group_by(time_of_day, level, sky)%>%
  summarise(total = n())%>%
  ggplot(aes(y = total, axis1 = time_of_day, axis2 = sky))+
  geom_alluvium(aes(fill = level), width = 0.02)+
  geom_stratum(width = 0.2)+
  geom_text(stat = "stratum", label.strata = TRUE)+
  scale_fill_got_d(option = "Daenerys", labels = c("High (>500)", "Low (<30)", "Mid (30 - 500)"))+
  scale_x_discrete(limits = c("Time of Day", "Sky"), expand = c(0.05, 0.05))+
  theme_light()+
  labs(y = "Total",
       title = "Aircraft Impact On Wildlife in North America",
       subtitle = "Most aircraft strike happen during the day at heights <30 while strikes at night occur at heights >500",
       caption = "Source: FAA | Visualization: Ifeoma Egbogah",
       fill = "Height")+
  theme(plot.title = element_text(family = "Nirmala UI Semilight"),
        plot.subtitle = element_text(family = "Nirmala UI Semilight"),
        axis.title = element_text(family = "Segoe UI Historic"),
        axis.text.y = element_text(family = "Segoe UI Historic"),
        legend.text = element_text(family = "Nirmala UI Semilight"),
        legend.title = element_text(family = "Nirmala UI Semilight"))


wildlife3 <- wildlife_impacts%>%
  filter(species != "Unknown bird - medium")%>%
  filter(species != "Unknown bird - small")%>%
  filter(species != "Unknown bird - large")%>%
  filter(species != "Unknown bird")%>%
  filter(species %in% c( "Brazilian free-tailed bat",  "Microbats", "Coyote", "Eastern red bat", "Red fox", "White-tailed deer", "Striped skunk", "Raccoon", "American alligator"))%>%
  filter(!is.na(time_of_day))%>%
  group_by(species, time_of_day)%>%
  summarise(total = n())%>%
  arrange(desc(total))%>%
  ggplot(aes(y = total, axis1 = species, axis2 = time_of_day))+
  geom_alluvium(aes(fill = time_of_day))+
  geom_stratum()+
  geom_label(stat = "stratum", label.strata = TRUE)+
  scale_fill_got_d(option = "Greyjoy")+
  scale_x_discrete(limits = c("Wildlife", "Time of Day"), expand = c(.05, .05))+
  theme_light()+
  theme(plot.subtitle = element_text(size = 8))+
  labs(y = "Total",
    title = "Aircraft Strike on Some Non-avaian Wildlife",
       subtitle = "Most strikes occur at night compared to avaian strikes which happen during the day",
       fill = "Time of Day",
       caption = "Source: FAA | Visualization: Ifeoma Egbogah")
  

wildlife4 <- wildlife_impacts%>%
  filter(species != "Unknown bird - medium")%>%
  filter(species != "Unknown bird - small")%>%
  filter(species != "Unknown bird - large")%>%
  filter(species != "Unknown bird")%>%
  filter(species %in% c("Gulls", "European starling", "Sparrows", "Blackbirds", "Morning dove", "Rock pigeon", "Barn swallow", "Hawks", "American robin", "Killdeer"))%>%
  filter(!is.na(time_of_day))%>%
  group_by(species, time_of_day)%>%
  summarise(total = n())%>%
  arrange(desc(total))%>%
  ggplot(aes(y = total, axis1 = species, axis2 = time_of_day))+
  geom_alluvium(aes(fill = time_of_day))+
  geom_stratum()+
  geom_label(stat = "stratum", label.strata = TRUE)+
  scale_fill_got_d(option = "Greyjoy")+
  scale_x_discrete(limits = c("Birds", "Time of Day"), expand = c(.05, .05))+
  theme_light()+
  theme(plot.subtitle = element_text(size = 8.5))+
  labs(y= "Total",
    title = "Aircraft Strike on Birds",
       subtitle = "Most strikes occur during the day compared to non-avaian strikes which happen at night", 
       fill = "Time of Day",
       caption = "Source: FAA | Visualization: Ifeoma Egbogah")


ggsave("wildlife.png", wildlife, width = 8, height = 8)
ggsave("wildlife1.png", wildlife1, width = 8, height = 8)
ggsave("wildlife2.png", wildlife2, width = 8, height = 8)
ggsave("wildlife3.png", wildlife3, width = 8, height = 8)
ggsave("wildlife4.png", wildlife4, width = 8, height = 8)
  

```


##Choropleth Map
```{r}

data("fips.state")
data("hawaii")
data("alaska")
data("us_states")



usa <- wildlife_impacts%>%
  filter(state != "N/A")%>%
  left_join(., fips.state, by = c("state" = "STUSAB"))

usa_1 <- usa%>%
  filter(!is.na(STATE_NAME))%>%
  group_by(STATE_NAME)%>%
  summarise(total = n())

usa_states <- us_states%>%
  left_join(., usa_1, by = c("NAME" = "STATE_NAME"))

hawaii <- hawaii%>%
  left_join(., usa_1, by = c("NAME" = "STATE_NAME"))

alaska <- alaska%>%
  left_join(., usa_1, by = c("NAME" = "STATE_NAME"))

usa_states1 <- st_transform(usa_states, 2163)
hawaii1 <- st_transform(hawaii, 2163)
alaska1 <- st_transform(alaska, 2163)

map <- ggplot()+
  geom_sf(data = usa_states1, aes(fill = total))+
  geom_sf(data = alaska1, aes(fill = total))+
  geom_sf(data = hawaii1, aes(fill = total))+
  scale_fill_got(option = "Tully")+
  theme_light()+
  theme_light()+
  theme(plot.title = element_text(family = "Nirmala UI Semilight"),
        plot.subtitle = element_text(family = "Nirmala UI Semilight"),
        legend.text = element_text(family = "Nirmala UI Semilight"),
        legend.title = element_text(family = "Nirmala UI Semilight"))+
  labs(fill = "Total",
       title = "Aircraft Strike On Wildlife in North America from 1990 - 2018",
       caption = "Source: FAA | Visualization: Ifeoma Egbogah")

ggsave("map.png", map, width = 8, height = 8)

```

