---
title: "NFL"
author: "Ifeoma Egbogah"
date: "2/11/2020"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)
library(grid)
library(scales)
library(RCurl)
library(cowplot)
library(ggimage)
library(extrafont)
font_import()
loadfonts(device = "win")


```


##Data
```{r}

attendance <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/attendance.csv')


standings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/standings.csv')


url_logo <- getURL("https://raw.githubusercontent.com/statsbylopez/BlogPosts/master/nfl_teamlogos.csv")

logo <- read.csv(text = url_logo)

missing_logo <- tibble(team2 = c("St. Louis Rams", "San Diego Chargers"),
                    url = as.factor( c("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1SdDuQie_F5MeJQf-0dtgxsUGevBX-Qi-QzZaMt-CsqM7MJLm&s",
                            "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQRF4fYdQQTKUM1pnt4LWFOj7F70CTFEmTsyVS3OKIO74i4D42b")))

attendance <- attendance%>%
  unite("team2", team:team_name, sep = " ", remove = FALSE)

standings <- standings%>%
  unite("team2", team:team_name, sep = " ", remove = FALSE)


```



##Ranking Of Home and Away Attendance
```{r}

attendance2 <- attendance%>%
  group_by(team2)%>%
  summarise(total2 = sum(total),
            total_home = sum(home)/10000000,
            total_away = sum(away)/10000000)%>%
  mutate(rank_away = rank(-total_away, ties.method = "min"),
         rank_home = rank(-total_home, ties.method = "min"),
         sq_rank = (rank_home^2) + (rank_away^2)/2,
         rank_order = rank(sq_rank, ties.method = "min"),
         team2 = fct_reorder(str_to_title(team2), rank_order),
         total_away = -total_away)


attendance2 <- attendance2%>%
  left_join(logo, by = c("team2" = "team"))


attendance3 <- attendance2%>% #filter teams with missing logo and join to missing_logo data
  filter(team2 == c("St. Louis Rams", "San Diego Chargers"))%>%
  select(-url)%>%
  left_join(missing_logo, by = ("team2" = "team2"))

attendance4 <- attendance2%>% #filter teams with logo
  filter(team2 != c("St. Louis Rams", "San Diego Chargers"))
  
attendance5 <- bind_rows(attendance3, attendance4) #bind the two datasets

attend_rank <- attendance5%>%
  mutate(team2 = fct_reorder(str_to_title(team2), rank_order))%>%
  ggplot(aes(x = team2))+
    geom_col(aes(y = total_home), fill = "darkred", colour = "white")+
    geom_text(aes(y = 8, 
                label = round(total_home, 1), 
            colour = if_else(total_home > 13, "white", "darkred")),
            size = 3,
            fontface = "bold",
            show.legend = FALSE)+
    geom_col(aes(y = total_away), fill = "grey85", colour = "white")+
    geom_text(aes(y = -6,
                label = round(total_away*-1, 1),
            colour = if_else(total_away < -14, "white", "grey45")),
            fontface = "bold",
            size = 3)+
    geom_text(aes(y = -30, x = 30), hjust = 0.5, vjust = 0, label = "HOME&", size = 7, colour = "darkred", family = "Tempus Sans ITC")+
    geom_text(aes(y = -25, x = 20), hjust = 0.4, vjust = 0, label = "AWAY", size = 7, colour = "grey45", family = "Tempus Sans ITC")+
  geom_image(aes(y = if_else(total_home >= 13, 23.5, 12), x = team2, image = url), size = 0.055, data = attendance5)+
    scale_y_continuous(limits = c(-30, 30), expand = c(0, 0))+
    scale_colour_identity()+
    coord_polar()+
    labs(title = "Ranking of Home and Away NFL Stadium Attendance",
         subtitle = "Not much variation in individual team's home and away attendance")+
    theme_nothing()+
   theme(axis.text.x = element_blank(),
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        plot.title = element_text(family = "Poor Richard", face = "bold", size = 25, hjust = 0.5),
        plot.subtitle = element_text(family = "Tempus Sans ITC"),
        plot.caption = element_text(family = "Tempus Sans ITC"))


##Legend
legend_col<- data.frame(Away = 10, ##chose any value to create a tile
                        Home = 10)

legend_away <- legend_col%>%
  ggplot(aes(Away, Home))+
  geom_tile(fill = "grey85")+
  scale_y_continuous(sec.axis = dup_axis())+
  geom_text(aes(Away, Home), label = "Away", family = "Tempus Sans ITC", fontface = "bold", colour = "grey45")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y.left = element_blank(),
        axis.title.y.right = element_text(angle = 0, vjust = 0.5, colour = "grey45", face = "bold"),
        panel.grid = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank())+
  labs(y = "",
       x = " ")


legend_home <- legend_col%>%
  ggplot(aes(Away, Home))+
  geom_tile(fill = "darkred")+
  scale_y_continuous(sec.axis = dup_axis())+
  geom_text(aes(Away, Home), label = "Home", family = "Tempus Sans ITC", fontface = "bold", colour = "red")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y.left = element_blank(),
        axis.title.y.right = element_text(angle = 0, vjust = 0.5, colour = "darkred", face = "bold"),
        panel.grid = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank())+
  labs(y = " ",
       x = " ")


plot1 <- ggdraw() +
  draw_plot(attend_rank, 0, 0, 1, 1)+
  draw_plot(legend_home, 0.9, 0.7, 0.1, 0.09)+
  draw_plot(legend_away, 0.9, 0.6335, 0.1, 0.09)


```


##Empirical Bayes Ranking of NFL Teams
```{r}

standings2 <- standings%>%
  group_by(team2)%>%
  summarise(total_wins = sum(wins),
            total_loss = sum(loss))%>%
  mutate(rank_wins = rank(-total_wins, ties.method = "min"),
         rank_loss = rank(total_loss, ties.method = "min"),
         sq_rank = (rank_wins^2) + (rank_loss^2)/2,
         rank_order = rank(sq_rank, ties.method = "min"),
         total = total_wins + total_loss,
         ratio = total_wins/(total_wins + total_loss))

shape_est <- MASS::fitdistr(standings2$ratio, dbeta,
                    start = list(shape1 = 1, shape2 = 1.09))

alpha0 <- shape_est$estimate[1]
beta0 <- shape_est$estimate[2]


standings2 <- standings2%>%
  mutate(eb_estimate = (total_wins + alpha0)/(total + alpha0 + beta0),
         total_loss_neg = -total_loss)%>%
         left_join(logo, by = c("team2" = "team"))

standings3 <- standings2%>% #filter teams with missing logo and join to missing_logo data
  filter(team2 == c("St. Louis Rams", "San Diego Chargers"))%>%
  select(-url)%>%
  left_join(missing_logo, by = ("team2" = "team2"))

standings4 <- standings2%>% #filter teams with logo
  filter(team2 != c("St. Louis Rams", "San Diego Chargers"))
  
standings5 <- bind_rows(standings3, standings4) #bind the two datasets

bayes_rank <- standings5%>%
  mutate(team2 = fct_reorder(team2, eb_estimate, .desc = TRUE))%>%
  ggplot(aes(team2))+
  geom_col(aes(y = total_wins), fill = "steelblue")+
  geom_text(data = standings2, aes(y = if_else(total_wins >= 50, 60, 68), 
                label = total_wins, 
            colour = if_else(total_wins >= 50, "white", "steelblue")),
            size = 3,
            fontface = "bold",
            show.legend = FALSE)+
  geom_col(aes(y = total_loss_neg), fill = "grey85")+
  geom_text(aes(y = if_else(total_loss_neg < -27, -60, -40), 
                label = total_loss, 
            colour = if_else(total_loss_neg < -27, "white", "grey45")),
            size = 3,
            fontface = "bold",
            show.legend = FALSE)+
  geom_image(aes(y = if_else(total_wins >= 182, 258, 205), x = team2, image = url), size = 0.055, data = standings5)+
  geom_text(aes(y = -250, x = 28), hjust = 0.25, vjust = 0, label = "WINS&", size = 7, colour = "steelblue", family = "Tempus Sans ITC")+
    geom_text(aes(y = -200, x = 22), hjust = 0.07, vjust = 0, label = "LOSSES", size = 7, colour = "grey45", family = "Tempus Sans ITC")+
  scale_y_continuous(limits = c(-270, 320))+
  scale_colour_identity()+
  coord_polar()+
  labs(title = "Empirical Bayes Ranking of Teams in the NFL",
       caption = "Source: Pro Football Reference | Visualization: @negbogah")+
  theme_nothing()+
  theme(axis.text.x = element_blank(),
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        plot.title = element_text(family = "Poor Richard", face = "bold", size = 25, hjust = 0.5),
        plot.subtitle = element_text(family = "Tempus Sans ITC"),
        plot.caption = element_text(family = "Tempus Sans ITC"))


##Legend
legend_col2<- data.frame(Wins = 10,
                        Loss = 10)

legend_loss <- legend_col2%>%
  ggplot(aes(Wins, Loss))+
  geom_tile(fill = "grey85")+
  scale_y_continuous(sec.axis = dup_axis())+
  geom_text(aes(Wins, Loss), label = "Loss", family = "Tempus Sans ITC", fontface = "bold", colour = "white")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y.left = element_blank(),
        axis.title.y.right = element_text(angle = 0, vjust = 0.5, colour = "grey45", face = "bold"),
        panel.grid = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank())+
  labs(y = "",
       x = " ")


legend_wins <- legend_col2%>%
  ggplot(aes(Wins, Loss))+
  geom_tile(fill = "steelblue")+
  scale_y_continuous(sec.axis = dup_axis())+
  geom_text(aes(Wins, Loss), label = "Wins", family = "Tempus Sans ITC", fontface = "bold", colour = "white")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y.left = element_blank(),
        axis.title.y.right = element_text(angle = 0, vjust = 0.5, colour = "steelblue", face = "bold"),
        panel.grid = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank())+
  labs(y = " ",
       x = " ")


plot2 <- ggdraw() +
  draw_plot(bayes_rank, 0, 0, 1, 1)+
  draw_plot(legend_wins, 0.9, 0.7, 0.1, 0.09)+
  draw_plot(legend_loss, 0.9, 0.6335, 0.1, 0.09)


nfl_plot <- plot_grid(plot1, plot2, ncol = 2)

#ggsave("~nfl_plot.jpeg", nfl_plot, width = 24, height = 16)

```



