---
title: "Donuts, Data, and D'oh - A Deep Dive into The Simpsons"
author: "Ifeoma Egbogah"
output: html_document
date: "2025-02-11"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)
library(png)
library(ggtext)
library(cowplot)

theme_set(theme_minimal())

theme_update(plot.margin = margin(5, 5, 5, 5),
             plot.background = element_rect(fill= "#E4DCD5", color = "#E4DCD5"),
             panel.background = element_rect(fill= "white", color = "transparent"),
             plot.caption = element_text(color = "#866D56", size = 7,
                                         lineheight = 1.8, margin = margin(7, 0, 7, 0)))

fam <- readPNG(here::here("2025", "Donuts, Data, and D'oh - A Deep Dive into The Simpsons",  "sim_fam.png"))

logo <- readPNG(here::here("2025", "Donuts, Data, and D'oh - A Deep Dive into The Simpsons", "simpson_logo.png"))



simpsons_characters <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-02-04/simpsons_characters.csv')
simpsons_episodes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-02-04/simpsons_episodes.csv')
simpsons_locations <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-02-04/simpsons_locations.csv')
simpsons_script_lines <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-02-04/simpsons_script_lines.csv')

```


```{r}

mill <- simpsons_episodes %>% 
  ggplot(aes(us_viewers_in_millions)) +
  geom_density(fill = "#ffc922",  colour = "#ffc922") +
  scale_x_continuous(position = "top") +
  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.25)) +
    
  theme(axis.ticks.x = element_blank(), 
        axis.title = element_text(size = 12, colour = "#866D56"),
        axis.text = element_text(size = 12, colour = "#866D56"),
        panel.grid = element_blank(),
       plot.title = element_textbox_simple(face = "bold", size = 14, lineheight = 1, padding = margin(10, 0, 20, 0), hjust = 0.5),
       
    panel.background = element_rect(color = "transparent", fill = "transparent"),
      plot.background = element_rect(color = "transparent",fill = "transparent")) +
    labs(title =  "Visualization of the Distribution of Simpsons' <span style = 'color:#ffc922;'>USA Viewers</span> and <span style = 'color:#cf1020;'>IMDB Ratings</span>",
      x = "US Viewers (millions)",
         y = "Density")



imdb <- simpsons_episodes %>% 
  ggplot(aes(imdb_rating)) +
  geom_density(fill = "#cf1020", colour = "#cf1020",) +
  scale_y_reverse() +
  theme(
        axis.title = element_text(size = 12, colour = "#866D56"),
        axis.text = element_text(size = 12, colour = "#866D56"),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(color = "transparent", fill = "transparent"),
      plot.background = element_rect(color = "transparent",  fill = "transparent")) +
    labs(x = "IMDB Ratings",
         y = " ",
         caption = "Data: Simpsons Dataset from Kaggle • Viz by Ifeoma Egbogah")


ggdraw() +
  draw_image(logo, x = 1, y = 0.61, hjust = 1.5, vjust = 1, width = 0.11, height = 0.2)+
  draw_image(fam, x = 1, y = 0.58, hjust = 1.3, vjust = 1.6, width = 0.13, height = 0.2)+
  draw_plot(mill, .5, .602, 1.007, .5, hjust = .5, vjust = 0) +
  draw_plot(imdb, .5, .6472, 1.007, .555, hjust = .5, vjust = 1) +
  theme(plot.margin = margin(45, 40, 40, 40)) 



ggsave(here::here("2025", "Donuts, Data, and D'oh - A Deep Dive into The Simpsons", "img.pdf"), width = 12, height = 6.347221, units = "in", device = cairo_pdf)

pdftools::pdf_convert(here::here("2025", "Donuts, Data, and D'oh - A Deep Dive into The Simpsons", "img.pdf"), format = "png", dpi = 300)

```

