---
title: "College Tuition, Diversity and Pay"
author: "Ifeoma Egbogah"
date: "4/30/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)
library(sf)
library(ggmap)
library(urbnmapr)
library(ggtext)
library(wesanderson)
library(extrafont)
loadfonts(device = "win")

theme_set(theme_light()) ##setting theme

pal2 <- wes_palette("Rushmore1", 5, type = "discrete") ##selecting colour palette

```


```{r}

tuition_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_cost.csv')

tuition_income <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_income.csv') 

salary_potential <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/salary_potential.csv')

historical_tuition <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/historical_tuition.csv')

diversity_school <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/diversity_school.csv')

```


##Dot density plot
```{r}

state <- get_urbn_map(map = "states", sf = TRUE)
state2 <- get_urbn_map(map = "counties", sf = TRUE)


school <- diversity_school%>%  ##getting the coordinates of each school
  count(name, state, sort = TRUE)%>%
  mutate(address = sprintf("%s, %s", name, state))%>%
  mutate_geocode(location = address, output = "latlon")


# credit to Jens von Bergmann for this algo function to round up numbers https://github.com/mountainMath/dotdensity/blob/master/R/dot-density.R

random_round <- function(x) {
    v=as.integer(x)
    r=x-v
    test=runif(length(r), 0.0, 1.0)
    add=rep(as.integer(0),length(r))
    add[r>test] <- as.integer(1)
    value=v+add
    ifelse(is.na(value) | value<0,0,value)
    return(value)
} 


# data frame of number of dots to plot for each category (1 for every 100 person)
diversity_school_join <- diversity_school%>%
  mutate(category = str_replace(category, "Two Or More Races", "Mixed"),
         category = str_replace(category, "American Indian / Alaska Native", "Native American"),
         category = str_replace(category, "Native Hawaiian / Pacific Islander", "Native Hawaiian"))%>%
  filter(enrollment > 0)%>%
  mutate(per_hundred = random_round(enrollment/100))%>%
  mutate(address = sprintf("%s, %s", name, state))%>%
  filter(category %in% c("White", "Black", "Asian", "Hispanic", "Mixed"))%>%
  left_join(school)%>%
  filter(!is.na(lon))%>%
  select(-n)%>%
  slice(sample(1:n()))
  

##Change the crs to 2163, extract the coordinates and then change from simple features to tibble data frame for plotting.

diversity_school_join2 <- st_as_sf(diversity_school_join, coords = c("lon", "lat"), crs = 4326)
diversity_school_join3 <- st_transform(diversity_school_join2, crs = 2163)


diversity_school_join4 <- diversity_school_join3%>% 
  mutate(lon = unlist(map(diversity_school_join3$geometry, 1)),
         lat = unlist(map(diversity_school_join3$geometry, 2)))

diversity_school_join4 <- as.data.frame(diversity_school_join4)


div_map <- ggplot()+
  geom_sf(data = state%>%
            filter(state_name != "Alaska",
                   state_name != "Hawaii"), fill = "transparent", colour = "grey65") +
  geom_point(data = diversity_school_join4%>%
               filter(state != "Alaska",
                      state != "Hawaii"), aes(lon, lat, colour = category, size = per_hundred))+
  scale_colour_manual(values = pal2)+
  theme_light()+
  theme(axis.text = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        plot.title = element_text(family = "Consolas", hjust = 0.5, size = 18),
        plot.subtitle = element_textbox_simple(colour = "grey"),
        plot.caption = element_text(family = "Consolas"),
        legend.text = element_text(family = "Kristen ITC"),
        legend.title = element_text(family = "Kristen ITC"))+
  labs(x = " ",
       y = " ",
       colour = "Ethnicity",
       size = "1 Dot per Hundred Person",
       title = "Dot Density Map of Diversity in US Universities and Colleges",
       subtitle = "The map shows a cluster of students of all ethnicity in the Eastern part of the US and California. The <span style = 'color: #F2300F'>WHITE</span> students population are however, generally scattered throughtout the universities all over the country. Large population of <span style = 'color: #0B775E'>HISPANIC</span> students in California, Texas and Florida states might suggest a preferance to study in universities in these states.",
       caption = "Source: TuitionTracker.org | Visualisation: @negbogah")

ggsave("~div_map.jpeg", div_map, width = 12, height = 8)

```



